[package]
name = "ceph-rust"
version = "0.1.0"
authors = ["Chris Jones <chris.jones@lambdastack.io>"]
license = "Apache-2.0"
readme = "README.md"
keywords = ["ceph", "storage"]
repository = "https://github.com/lambdastackio/ceph-rust"
homepage = "https://github.com/lambdastackio/ceph-rust"
documentation = "https://lambdastackio.github.io/ceph-rust/ceph-rust"
description = """
Ceph-rust is a rust-lang specific interface to Ceph librados. Under heavy dev *do not use* at this time.
"""

[dependencies]
libc = "0.2"
lsio = "0.1"
