[package]
name = "ceph-rust"
version = "0.1.2"
authors = ["Chris Jones <chris.jones@lambdastack.io>"]
license = "Apache-2.0"
readme = "README.md"
keywords = ["ceph", "storage"]
repository = "https://github.com/lambdastackio/ceph-rust"
homepage = "https://github.com/lambdastackio/ceph-rust"
documentation = "https://lambdastackio.github.io/ceph-rust/ceph-rust"
description = """
Ceph-rust is a rust-lang specific interface to Ceph librados. You can create a Ceph development environment with the
Chef automation tools I created from the following: https://github.com/bloomberg/chef-bcs. It uses the ceph-chef cookbook
I created and manage at github.com/ceph/ceph-chef. It will build out a full Ceph environment which you can then use
for development etc. See README.md for details.
"""

[dependencies]
libc = "0.2"
lsio = "0.1"

[[bin]]
doc = true
name = "ceph"
path = "examples/ceph.rs"
